#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#undef DEBOUNCE
#define DEBOUNCE 10

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "BE3md/x9DOKW"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 12

#define TAPPING_TERM_PER_KEY

